customer_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendCustomerBundle:Customer:show" }

customer_new:
    pattern:  /new_customer
    defaults: { _controller: "BackendCustomerBundle:Customer:new" }

customer_create:
    pattern:  /create_customer
    defaults: { _controller: "BackendCustomerBundle:Customer:create" }
    requirements: { _method: post }

customer_edit:
    pattern:  /{id}/edit_customer
    defaults: { _controller: "BackendCustomerBundle:Customer:edit" }

customer_update:
    pattern:  /{id}/update_customer
    defaults: { _controller: "BackendCustomerBundle:Customer:update" }
    requirements: { _method: post|put }

customer_delete:
    pattern:  /{id}/delete_customer
    defaults: { _controller: "BackendCustomerBundle:Customer:delete" }
    requirements: { _method: get|post|delete }

customer_profile:
    path: /customer_profile
    defaults: { _controller:BackendCustomerBundle:Customer:profile }

customer:
    pattern:  /{search}
    defaults: { _controller: "BackendCustomerBundle:Customer:index", search: '' }

