Backend\CustomerBundle\Entity\Customer:
    properties:
        name:
            - NotBlank: { message: Olvido ingresar el Nombre }
            - Length: 
                min: 2
                max: 100
                minMessage: "El nombre debe tener al menos 2 carácteres"
                maxMessage: "El nombre debe tener 100 carácteres máximo"
        dni:
            - Length: 
                min: 2
                max: 100
                minMessage: "El dni debe tener al menos 2 carácteres"
                maxMessage: "El dni debe tener 100 carácteres máximo"
        phone:
            - Length: 
                min: 4
                max: 100
                minMessage: "El teléfono debe tener al menos 4 carácteres"
                maxMessage: "El teléfono debe tener 100 carácteres máximo"        
        birthday:
            - Date: { message: Fecha fuera de rango } 
        lastname:  
            - NotBlank: { message: Olvido ingresar el Apellido }
            - Length: 
                min: 2
                max: 100
                minMessage: "El Apellido debe tener al menos 2 carácteres"
                maxMessage: "El Apellido debe tener 100 carácteres máximo"
        email: 
            - NotBlank: { message: Ingrese un email }
            - Email: { message: Ingrese un email válido }
            - Length: 
                min: 4
                max: 100
                minMessage: "El email debe tener al menos 4 carácteres"
                maxMessage: "El email debe tener 60 carácteres máximo"  
        groups:
            - NotBlank: { message: Debe seleccionar al menos un Grupo }  

