frontend_vercarrito:
    pattern:  /carrito
    defaults: { _controller: FrontendHomeBundle:Producto:showCarrito }

frontend_product_filter:
    pattern:  /frontProductosFilter/{id}/{search}
    defaults: { _controller: FrontendHomeBundle:Producto:getProductsByTiendaFilter , search: ''}

frontend_llega:
    pattern:  /llega
    defaults: { _controller: FrontendHomeBundle:Producto:llega }    

frontend_pedido:
    pattern:  /realizar_pedido
    defaults: { _controller: FrontendHomeBundle:Producto:realizarPedido }

