parameters:
#    backend_admin.example.class: Backend\CustomerAdminBundle\Example

services:
#    backend_admin.example:
#        class: %backend_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     