customer_principal:
    pattern:  /
    defaults: { _controller: BackendCustomerAdminBundle:Principal:index }

customer_blank:
    pattern:  /blank
    defaults: { _controller: BackendCustomerAdminBundle:Principal:blank }

customer_profile:
    pattern:  /profile
    defaults: { _controller: BackendCustomerAdminBundle:Principal:profile }

customer_login:
    pattern: /login
    defaults: { _controller: BackendCustomerBundle:Default:login }

customer_auth:
    pattern: /login_check

customer_logout:
    path: /logout 

customer_direccion:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/direccion.yml"
    prefix:   /direccion    

   


            