customer_principal:
    pattern:  /
    defaults: { _controller: BackendCustomerAdminBundle:Principal:index }

customer_blank:
    pattern:  /blank
    defaults: { _controller: BackendCustomerAdminBundle:Principal:blank }

customer_profile:
    path: /customer_profile
    defaults: { _controller:BackendCustomerAdminBundle:Principal:profile }

customer_login:
    pattern: /login
    defaults: { _controller: BackendCustomerBundle:Default:login }

customer_auth:
    pattern: /login_check

customer_logout:
    path: /logout 

customer_direccion:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/direccion.yml"
    prefix:   /direccion    

customer_sucursal:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/sucursal.yml"
    prefix:   /sucursal    

customer_producto:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/producto.yml"
    prefix:   /producto    
   
customer_horario:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/horario.yml"
    prefix:   /horario  

customer_variedad:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/variedad.yml"
    prefix:   /variedad  

            