barrio_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Barrio:new" }

barrio_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:Barrio:exportar" }
    
barrio_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Barrio:create" }
    requirements: { _method: post }

barrio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Barrio:edit" }

barrio_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Barrio:update" }
    requirements: { _method: post|put }

barrio_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Barrio:delete" }
    requirements: { _method: post|delete }
    
barrio_zona:
    pattern:  /getbarrio
    defaults: { _controller: "BackendAdminBundle:Barrio:getBarrioByZona" }


barrio:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:Barrio:index" , search: ''}
