horario_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Horario:new" }

horario_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:Horario:exportar" }
    
horario_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Horario:create" }
    requirements: { _method: post }

horario_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Horario:edit" }

horario_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Horario:update" }
    requirements: { _method: post|put }

horario_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Horario:delete" }
    requirements: { _method: post|delete }
        
horario:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:Horario:index" , search: ''}
