admin_producto_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Producto:new" }

admin_producto_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:Producto:exportar" }
    
admin_producto_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Producto:create" }
    requirements: { _method: post }

admin_producto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Producto:edit" }

admin_producto_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Producto:update" }
    requirements: { _method: post|put }

admin_producto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Producto:delete" }
    requirements: { _method: post|delete }

admin_producto:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:Producto:index" , search: ''}
