horario_new:
    pattern:  /new
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:new" }

horario_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:exportar" }
    
horario_create:
    pattern:  /create
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:create" }
    requirements: { _method: post }

horario_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:edit" }

horario_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:update" }
    requirements: { _method: post|put }

horario_load_horario:
    pattern:  /loadHorario
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:loadHorario" }

horario_save_horario:
    pattern:  /saveHorario
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:toSaveHorario" }


horario_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:delete" }
    requirements: { _method: post|delete }
        
horario:
    pattern:  /{search}
    defaults: { _controller: "BackendCustomerAdminBundle:Horario:index" , search: ''}
