zona_new:
    pattern:  /new
    defaults: { _controller: "BackendCustomerAdminBundle:Zona:new" }

zona_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendCustomerAdminBundle:Zona:exportar" }
    
zona_create:
    pattern:  /create
    defaults: { _controller: "BackendCustomerAdminBundle:Zona:create" }
    requirements: { _method: post }

zona_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendCustomerAdminBundle:Zona:edit" }

zona_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendCustomerAdminBundle:Zona:update" }
    requirements: { _method: post|put }

zona_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendCustomerAdminBundle:Zona:delete" }
    requirements: { _method: post|delete }

zona_all: 
    pattern:  /la
    defaults: { _controller: "BackendCustomerAdminBundle:Zona:getZonas" }
    
zona:
    pattern:  /{search}
    defaults: { _controller: "BackendCustomerAdminBundle:Zona:index" , search: ''}
