frontend_homepage:
    pattern:  /
    defaults: { _controller: FrontendHomeBundle:Home:index }

frontend_menuZona:
    pattern:  /menuZona
    defaults: { _controller: FrontendHomeBundle:Home:menuZona }
    
frontend_menuCategoria:
    pattern:  /menuCategoria
    defaults: { _controller: FrontendHomeBundle:Home:menuCategoria } 

frontend_tiendas:
    pattern:  /tiendas
    defaults: { _controller: FrontendHomeBundle:Home:getTiendas }


frontend_premium:
    pattern:  /tiendas_premium
    defaults: { _controller: FrontendHomeBundle:Home:getTiendasPremium }    
       
    